### ISSUE TITLE
Notification configuration enhancement to alert2

### ISSUE THREAD

**Issue by kenwiens** [redstone99/hass-alert2#1]
For me, the most complex part of my alerts are notifications - who to send them to, and on what platform.  I travel a lot, and before leaving, I go into a dashboard and select who will get notifications and on what platform.  It works very well for me and I couldn't really have alerts without this.  Here is that dashboard:

![image](https://github.com/user-attachments/assets/2072dee8-af10-46f4-92d8-31c12ad61deb)

 Sometimes when I travel, other potential notification receivers are also away - so I don't want to send them notifications when they wouldn't be able to do anything about them.

Without this, I would need to go in a modify code every time I travel. 

I was wondering if you had any thoughts about incorporating this kind of functionality into Alert2?  While what I have shown above generally suffices for my notification needs - it could be significantly enhanced (I might for example classify alerts/notifications into critical or non-critical and select recipients based on that attribute.)  The problem with what I have, is that every "alert automation" I create needs to call my notification automation to determine who to send notification to  and how.

If you are interested, I'd be glad to discuss, test etc.

Thanks!

**Comment by redstone99** [comment]
Hi - thanks for raising the first issue! I'm totally up for enriching how notifiers are specified. Let me know if I'm understanding this correctly.  It sounds like who you notify and what platform you use to notify them changes based on:
1. whether you're traveling or not
2. the priority of the individual alert

How do you manage this today? I imagine you declare a bunch of notification targets like "kenn_text" and "sara_text"?

My first thought is that I could make the `notifier` parameter take a template that evaluates to a set of notification targets.  Then you could say something like:

    - domain: garage
      name: door_open
      condition: "{{ ... }}"
      notifier: "{{ [ kenn_text ] if states('binary_sensor.traveling')|bool else [ sara_text ] }}"

If the logic gets complex and you use it in many alerts, you could move it into a template entity and refer to the template entity in the notifier.  So the template entity would be a like a "notification group".  And you could declare different groups for high-priority and low-priority alerts:

    sensor:
      - platform: template
        sensors:
           lopri_notifiers:
              value_template: "{{ [ kenn_text ] if states('binary_sensor.traveling')|bool else [ sara_text ] }}"
           hipri_notifiers:
              value_template: "{{ [ jim_text ] if states('binary_sensor.traveling')|bool else [ jane_text ] }}"
    alert2:
      alerts:
        - domain: garage
          name: door_open
          condition: "{{ ... }}"
          notifier: "{{ states('sensor.lopri_notifiers') }}"

Alternatively, I could imagine adding a parameter specifying alert priority explicitly in the alert.  I suppose this would be useful if you wanted to distinguish them in the UI somehow.

Thoughts?

**Comment by kenwiens** [comment]
Hi - thanks for raising the first issue! I'm totally up for enriching how notifiers are specified. Let me know if I'm understanding this correctly. It sounds like who you notify and what platform you use to notify them changes based on:

whether you're traveling or not

-  _It's a bit more complicated than that.  My travels might be many months in length, so the notification contacts will change many times.  One week it might be my son and his wife, and the next week my son might also be out of town (and doesn't want to get my notifications - as he can't react to a water leak for example)), so it is his wife and my daughter who get notified.  Sometimes my family members are all away so I send notifications to a neighbour.  As other peoples travel plans change frequently, I need to adjust who gets notifications (to not take advantage of the good nature of my neighbours :-)  It changes constantly - thus that dashboard I showed you so that I can easily change who get notified. using my phone or laptop_ 

the priority of the individual alert

- _this would be a nice to have.  currently I don't have this implemented - so everyone that gets selected to receive notifications get them all.  If you wnated to consider this without this feature that would be fine, we could look at this as an enhancement further down the road_

How do you manage this today? I imagine you declare a bunch of notification targets like "kenn_text" and "sara_text"?

- _In the dashboard I showed you, each entity is an input Boolean eg "input_boolean.advise_ken_via_wa".  Then I have a file called notify.yaml that includes all my notification entries, for example:_

```
# Ken via WhatsApp    
  - name: "NOTIFY_KEN_VIA_WHATSAPP"
    platform: rest
    resource: https://api.callmebot.com/whatsapp.php
    data:
      source: HA
      phone: +1403813xxxx #enter your phone number here
      apikey: xxxxxx #enter your apikey here (see Setup above)

```

- _Then each alert has its own automation.  In this automation it sets a text field with the appropriate message based on where the alert notification is going. (to send an alexa message, or to send text/whatsapp messages or HA alerts.)  Here is an action extract from one of them_

```
  - data:
      value: >-
        A moisture leak has been detected.  The sensor reporting the leak is 
        {{trigger.event.data.new_state.attributes.friendly_name }}
    target:
      entity_id: input_text.advise_notification_message_for_alexa
    action: input_text.set_value
  - data:
      value: >-
        A water leak has been detected.  The sensor reporting the leak is 
        {{trigger.event.data.new_state.attributes.friendly_name }}. The master
        water valve has been turned off.  It can be turned back on using the
        button in the main view in the Home Asssitant App
    target:
      entity_id: input_text.advise_notification_message_via_text
    action: input_text.set_value
  - data: {}
    target:
      entity_id: script.alerts_general_purpose_alerts_text_and_alexa
    action: script.turn_on
  - data:
      value: >-
        A water leak has been detected.  I have turned off the main water valve
        for the house.
    target:
      entity_id: input_text.advise_notification_message_for_alexa
    action: input_text.set_value
```

- _After the messages are created, it calls a script to do the magic of sending the notification.  In this script it individually checks every input_boolean to see who/where it should send notifications and then sends as requested.  Here is a tiny sample of the code in that script (it is long as every option must be evaluated)_

 ```
 - if:
      - condition: state
        entity_id: input_boolean.advise_megan_via_text
        state: "on"
    then:
      - data:
          message: "{{states('input_text.advise_notification_message_via_text')}}"
        action: notify.notify_mb_via_txt
  - if:
      - condition: state
        entity_id: input_boolean.advise_ken_via_wa
        state: "on"
    then:
      - data:
          message: "{{states('input_text.advise_notification_message_via_text')}}"
        action: notify.notify_ken_via_whatsapp  

```

- _Because of the dynamic nature of my travels, and the need to change who get notified frequently, the dashboard concept I presented above is a vital component.  Basically a GUI to set the notification recipient is crucial. I suspect other users would like the flexibility to send notification to others when they are out of town, and I may be more of an extreme case (but that just makes me a better tester!)  Perhaps I set the input_booleans in my dashboard and somehow I pass you the list of input booleans and how each one links to the appropriate notifier.  I really haven't thought through which parts make sense to put in alert2 and which ones don't.  I'm sure you are better at figuring that part out than I am._


My first thought is that I could make the notifier parameter take a template that evaluates to a set of notification targets. Then you could say something like:

- domain: garage
  name: door_open
  condition: "{{ ... }}"
  notifier: "{{ [ kenn_text ] if states('binary_sensor.traveling')|bool else [ sara_text ] }}"
If the logic gets complex and you use it in many alerts, you could move it into a template entity and refer to the template entity in the notifier. So the template entity would be a like a "notification group". And you could declare different groups for high-priority and low-priority alerts:

sensor:
  - platform: template
    sensors:
       lopri_notifiers:
          value_template: "{{ [ kenn_text ] if states('binary_sensor.traveling')|bool else [ sara_text ] }}"
       hipri_notifiers:
          value_template: "{{ [ jim_text ] if states('binary_sensor.traveling')|bool else [ jane_text ] }}"
alert2:
  alerts:
    - domain: garage
      name: door_open
      condition: "{{ ... }}"
      notifier: "{{ states('sensor.lopri_notifiers') }}"
Alternatively, I could imagine adding a parameter specifying alert priority explicitly in the alert. I suppose this would be useful if you wanted to distinguish them in the UI somehow.

Thoughts?
