### ISSUE TITLE
Alert2 triggered by condition_off?

### ISSUE THREAD

**Issue by flimofly** [redstone99/hass-alert2#11]
As you know I have this alert2 (see below for yaml), which triggers when the washing machine is ready (`input_boolean.washer_ready` is set to `on `by a blueprint when power use drops below a certain threshold according to a specific pattern) and fires _until_ the washer door is opened.  When the door is opened for 2 seconds, the input boolean indicating that the washer is ready is set to `off`.  This functions well.

Today I saw that the input boolean was erroneously set to `on` even though the machine had been emptied.  Strangely enough, this caused the alert to function backwards, i.e. it was triggered by opening the door. In the UI this looks like this:

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/752338dc-62aa-44c1-8c13-3adeb75fa5fd" />

I could still understand it if the alert started firing again when `condition_off` becomes false again _and_ the input boolean is (erroneously) still set to on but I can't quite wrap my around what's happening here.

```
alert2:
  alerts:
    - domain: washer
      name: "wet_laundry"
      trigger_on:
        - trigger: state
          entity_id: input_boolean.washer_ready
          to: "on"
      condition_off: "{{ is_state('binary_sensor.doorsensor_opening','on') }}"
      message: "Wet laundry in machine!"
      done_message: "Emptied!"
      title: Washer
      reminder_frequency_mins: [ 1, 10, 20, 60, 120 ]
      notifier: 
        - mobile_app_iphone
```
