### ISSUE TITLE
Generator in trigger doesn not work

### ISSUE THREAD

**Issue by arboeh** [redstone99/hass-alert2#12]
This does not work for me, I guess it is not possible to use an attribute of a generator in a triggers' entity_id.
I want to trigger an alert only if nobody is at home and someone opens some window during total absence.

```
  - generator_name: window_away_opened
    generator:
      - { id: gaeste_wc, text: 'WC-Fenster' }
      - { id: badezimmer, text: 'Fenster Bad' }
      - { id: garage, text: 'Garage' }
    domain: window
    name: 'alert_{{ id }}_away_opened'
    friendly_name: '{{ text }}'
    priority: 'high'
    trigger_on:
      - platform: state
        entity_id: 'binary_sensor.aqara_ws_{{ id }}'
        to: 'on'
    condition_on: "{{ is_state('group.companion_phones', 'not_home') }}"
    trigger_off:
      - platform: state
        entity_id: 'binary_sensor.aqara_ws_{{ id }}'
        to: 'off'
      - platform: state
        entity_id: group.companion_phones
        to: 'home'
    title: '{{ text }}'
    ............
```

**Comment by redstone99** [comment]
Just released v1.12 which supports generator vars in trigger fields that allow templates (like `trigger: template`).   So the following should now work:
````
  - domain: test
    name: my_alert
    generator: ...
    trigger_on:
      - trigger: template
        value_template: "{{ states(genEntityId) }}"
````

Let me know what you think.
