### ISSUE TITLE
[feature] Generator name collisions should probably be an error

### ISSUE THREAD

**Issue by LordMike** [redstone99/hass-alert2#15]
I tried out the generator to make two alerts, like the free disk space example, and I only got one alert2 entity. Turns out, I didn't template my domain/name combination, so all generated alert2 entities were essentially the same name. 

I hope that only one of the entities "survives", and that they don't mess up each others internal state - although I did have a lot of weird behavior that was solved by an HA restart - possibly entirely unrelated. 

Example:

```yaml
  - domain: alert01
    name: "my_name" # <-- no template
    condition: false
    supersedes: "{{ genPrevDomainName }}"
    generator_name: alertgen_demo
    generator:
      - { name: warning }
      - { name: critical }
```

Created alerts:
![Image](https://github.com/user-attachments/assets/4af884ff-b24a-4a76-a40a-754504473d7b)

Ideas:
- check uniqueness on all generated alert names (maybe even globally) and don't generate any on collisions
  - guarantees the user (me) will notice
- skip any duplicated name alert2 entities, but throw / show an error through the error alert/persistent notification/default notifier as other configuration errors
