### ISSUE TITLE
interaction with custom:paper-buttons-row - where the bug ?

### ISSUE THREAD

**Issue by Masterz69** [redstone99/hass-alert2#16]
Previously created alert, which in in state `off` state, shown in `custom:paper-buttons-row` with no issues.

Recently created (after v1.12 installed) have state `has never fired` instead of `on/off`.
And by some reason `custom:paper-buttons-row` fails to show them.

![Image](https://github.com/user-attachments/assets/c86ef0c5-5da6-4ec1-8e95-d3c5b0fa9a66)

As well when using `auto-entities` see following - it also fails to show state of just created and never fired alerts:

![Image](https://github.com/user-attachments/assets/2131ec54-59eb-4090-b5a4-8f7dec2d6b79)

```yaml
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
  state_color: true
filter:
  include:
    - options: {}
      domain: alert2
  exclude: []
```
```yaml
type: entities
entities:
  - type: custom:paper-buttons-row
    base_config:
      name: false
    buttons:
      - - name: 'HA'
          icon: 'mdi:alert-outline'
          entity: alert2.process_ha
. . .
```

**Comment by redstone99** [comment]
Hi @Masterz69 , thanks for raising the issue. So there are two kinds of alerts, event alerts and condition alerts.
The state of a condition alert is either "on" or "off.  It is "off" if it has never fired.  It is "on" while the offending condition is true.

An event alert doesn't have a concept of being on or off. It represents something that happened at a single point in time (for example a bad MQTT message arrived).   The state of an event alert is the timestamp of the last time the event happened.  If the event has never happened, the state is the empty string.

The alert2-overview UI card has some extra logic to substitute the empty string with "has never fired".
So that's why you see the empty string displayed in auto-entities and "has never fired" in the overview card.

So I guess there are two questions:
1. what would you like to see displayed as the state of an event alert that has never fired?
2. how could that be implemented?

Let me know your thoughts.

**Comment by Masterz69** [comment]
```yaml

      - domain: process
        name:   ABS
        friendly_name: "Alert on Process ABS"
        condition: "{{ states(sensor.servion_satellite_process_audiobookshelf)|int <1 }}"

      - domain: failure
        name: offline
        friendly_name: "Alert on Device Offline"
        trigger:
          - platform: state
            entity_id: 
              - binary_sensor.sns_ups_in_power
...
            to: "off"
            for:
              minutes: 5
        condition: true

```

**Comment by redstone99** [comment]
Oh, so you want reminders for alerts that haven't been acked, is that right?    I distinguish between the underlying problematic condition (eg no ping response) and whether the condition has been acked. I could imagine adding a flag to specify to keep sending reminders for unacked alerts.

If you really want an alert who'se state reflects whether it has been acked, you could do something close with:
````
      - domain: failure
        name: ping
        friendly_name: "Alert on Ping Lost"
        trigger_on:
          - platform: state
            entity_id: 
              - binary_sensor.ping_servion
...
            to: 'off'
        manual_off: true
````
and then set an automation that, when the alert is acked, invokes a service call to turn off the alert.   But it's rather hacky.
