### ISSUE TITLE
Cannot create event alert through UI / Ghost entities

### ISSUE THREAD

**Issue by cerebrate** [redstone99/hass-alert2#8]
I ran into this issue while migrating my existing alerts over to the UI. One of them was my test event alert, which I define thus:

```
- domain: test
  name: event_alert
  friendly_name: Test Event Alert
  trigger:
    - platform: state
      entity_id: input_button.test_event_alert
  message: The test event alert has been fired. No action is necessary.
```

Trying to create it gives me this error:

![Image](https://github.com/user-attachments/assets/81a9c2d2-1f3f-4176-bd9b-4d4706739a5f)

Which is one thing. Another problem, however, is that while it doesn't create a functioning alert and doesn't show up in the Alert2 Manager card, an entity for it is actually created:

![Image](https://github.com/user-attachments/assets/11669146-40be-49a3-820f-3809a82c53ac)

Which can't be deleted: the entity can't be deleted manually (does not have a unique ID), nor can it be deleted or updated via the Alert2 Manager (which can't find a UI-created event by that name), nor can you create a new event with the same name (hence the _2 and _3 above), because a duplicate already exists...
